name: Gitflow Release

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Gitflow action to perform'
        required: true
        type: choice
        options:
          - release-start
          - release-finish
      version:
        description: 'Release version (for release-start and release-finish, e.g., 1.18.0)'
        required: false
        type: string

jobs:
  release:
    uses: dataliquid/github-actions/.github/workflows/gitflow-release.yml@main
    with:
      action: ${{ inputs.action }}
      version: ${{ inputs.version }}
      java-version: '8'  # Optional, defaults to 8
      java-distribution: 'temurin'  # Optional, defaults to temurin
      runs-on: 'ubuntu-latest'  # Optional, defaults to ubuntu-latest